import { hexToBN } from "../../utils/utils";
import { debug } from "../../utils/debugger";
import { readStorage } from "../CarmineStaking/calls";
import { QueryFunctionContext } from "@tanstack/react-query";
import { CarmineApi } from "@carmine-options/sdk/api";

export type Eligible = {
  eligible: true;
  claimable: bigint;
  claimed: bigint;
  proof: string[];
};

type NotEligible = {
  eligible: false;
};

export type ProofResult = Eligible | NotEligible;

export const getProof = async (address: string): Promise<ProofResult> => {
  const airdropRequest = CarmineApi.airdrop(address);

  const claimedPromise = readStorage(address);

  const [airdropData, claimed] = await Promise.all([
    airdropRequest,
    claimedPromise,
  ]);

  if (airdropData === null) {
    return { eligible: false };
  }

  const total = hexToBN(airdropData[1]);
  const diff = total - claimed;
  const claimable = diff < 100n ? 0n : total - claimed;

  debug("CARM token claim data:", {
    total: total.toString(10),
    claimed: claimed.toString(10),
    claimable,
  });

  return {
    eligible: true,
    proof: airdropData, // proof generated by backend
    claimable, // how much can be claimed
    claimed: claimed, // how much has been claimed
  };
};

export const getAirdropDataQuery = async ({
  queryKey,
}: QueryFunctionContext<[string, string]>): Promise<ProofResult> => {
  const address = queryKey[1];
  return getProof(address);
};
